announce_interval: 3
check_interval: 3
send_interval: 10
post_directory: Z:/Neural/RawPictures/islabot
best_directory: Z:/Neural/SortedPictures/Best
crsd_directory: Z:/Neural/SortedPictures/Crsd
webui_url: http://127.0.0.1:7860
