announce_interval: 3
check_interval: 3
send_interval: 10
post_directory: Z:/Neural/RawPictures/islabot
best_directory: Z:/Neural/SortedPictures/Best
crsd_directory: Z:/Neural/SortedPictures/Crsd
webui_url: http://127.0.0.1:7860
enable_image_announce: 0
crsd_threshold: 3
best_threshold: 3
del_threshold: 3
db_full_path: Z:/Neural/RawPictures/islabot/db/isla.db